# Custom Language File for Launcher Customizer

[ejs.app]
title = "May's Story"

[ejs.landing]
mediaChzzkURL = "https://github.com/BabyBear7/launcher-demo"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/QHHZNcY6BY"

[ejs.settings]
sourceGithubLink = "https://github.com/qdakim/MaysStory"
supportLink = "https://github.com/qdakim/MaysStory/issues"

[ejs.welcome]
welcomeHeader = "May's Story에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
